import React from 'react';
import { BrutalBadge } from './BrutalBadge';
import { Cpu } from 'lucide-react';

export function ModelBadge({ meta }) {
  if (!meta || !meta.model) return null;

  const { provider, model } = meta;

  // Make the model name look pretty
  let displayName = model;
  if (model.includes('/')) {
    displayName = model.split('/').slice(-1)[0]; // e.g. "google/gemini-2.5-flash" -> "gemini-2.5-flash"
  }
  
  // Format model nicely
  displayName = displayName
    .replace('gemini-2.5-flash', 'Gemini 2.5 Flash')
    .replace('gemini-2.5-pro', 'Gemini 2.5 Pro')
    .replace('gpt-4o-mini', 'GPT-4o Mini')
    .replace('gpt-4o', 'GPT-4o')
    .replace('claude-sonnet-latest', 'Claude Sonnet (Latest)')
    .replace('claude-3-5-sonnet', 'Claude 3.5 Sonnet');

  const providerLabel = provider === 'openrouter' ? 'via OpenRouter' : 'Direct';

  return (
    <div className="inline-flex items-center gap-2 mt-2">
      <BrutalBadge variant={provider === 'openrouter' ? 'info' : 'success'} size="sm">
        <span className="flex items-center gap-1">
          <Cpu className="w-3 h-3" />
          Generated by {displayName} ({providerLabel})
        </span>
      </BrutalBadge>
    </div>
  );
}
